data:
  img_size: 448
  dataset: flowers
  batch_size: 32
  resize: 600
  color: 0.4
  data_root: 'datasets/'
  log_path: 'logs/'
model:
  baseline_model: False
  drop_path: 0.
  label_smooth: 0.
  name: 'dinov2_vitb'
  pre_suffix: '.pth'
parameters:
  vote_perhead: 24
  loss_alpha: 0.4
  total_num: 126
  fix: True
  dsm: True
  cam: True
  assess: False
train:
  lr: 0.02
  epochs: 50
  clip_grad: True

#  freeze_backbone: True
#misc:
#  throughput: True
#  eval_mode: True